language: cpp

compiler:
        # Unfortunately, clang does not support OpenMP yet - see OpenMP/Clang on github for alternative
        #- clang
        - gcc

before_install:
        - if [ "$CXX" = "clang++" ]; then sudo apt-get install libstdc++-4.9-dev llvm-3.5 llvm-3.5-dev clang-3.5; fi
        - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
        - if [ "$CXX" = "clang++" ]; then $CXX --version; fi
        - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
        - sudo apt-get install cmake

before_script:
        - mkdir build
        - cd build
        - cmake ..

script: make

after_success: make clean
