language: cpp

compiler:
        # Unfortunately, clang does not support OpenMP yet - see OpenMP/Clang on github for alternative
        #- clang
        - gcc

env: BUILD_TYPE=Debug

before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

before_script:
        - mkdir build
        - cd build
        - cmake ..

script: make

after_success: make clean
